name: Build and Push Images

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go mod download
      - name: Generate code
        run: go generate
      - name: Test with Go
        run: go test ./...

  build_and_push:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Setup docker buildx' 
        uses: docker/setup-buildx-action@v3

      - name: 'Build and Push Image' 
        run: |
          docker buildx create --use --name=crossplat --node=crossplat
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/t-muehlberger/sharepass:latest \
            --push \
            .
